import json
import os
from pathlib import Path

# MODEL_NAME = "deepseek-chat"
MODEL_NAME = "qwen3-32b"
# ================= Config =================
# Set this to the JSON file generated by the previous run.
RESULT_FILE = f"D:/LIHAOZE/bishe/thecode/ddd/dataset_v1/{MODEL_NAME}_RAG_COT2_Results.json"
# RESULT_FILE = f"D:/LIHAOZE/bishe/thecode/ddd/dataset_v2/{MODEL_NAME}_RAG_COT2_Results.json"
# =======================================

def safe_div(a, b):
    """Safe division that avoids division by zero."""
    return a / b if b != 0 else 0.0

def analyze(file_path):
    if not os.path.exists(file_path):
        print(f"❌ 错误：找不到文件 {file_path}")
        return

    print(f"📂 正在加载分析文件: {file_path}")
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception as e:
        print(f"❌ JSON 解析失败: {e}")
        return

    # 1. Initialize counters.
    tp = 0  # True positive (GT=1, Pred=1)
    tn = 0  # True negative (GT=0, Pred=0)
    fp = 0  # False positive (GT=0, Pred=1)
    fn = 0  # False negative (GT=1, Pred=0)

    # Detailed stats: details[ground-truth label][prediction correctness][reason correctness].
    # keys: 1 (Vulnerable), 0 (Safe)
    # sub-keys: "p_corr_r_corr", "p_corr_r_wrong", "p_wrong_r_corr", "p_wrong_r_wrong"
    details = {
        1: {"corr_corr": 0, "corr_wrong": 0, "wrong_corr": 0, "wrong_wrong": 0},
        0: {"corr_corr": 0, "corr_wrong": 0, "wrong_corr": 0, "wrong_wrong": 0}
    }

    total = len(data)
    
    for item in data:
        # Read fields and normalize types.
        gt = int(item.get("gt_label", item.get("label", 0)))
        pred_is_vul = bool(item.get("pred_is_vul", False))
        
        # Judge results: 1 means correct, 0 means wrong.
        judge_pred_correct = int(item.get("prediction_correct", 0))
        judge_reason_correct = int(item.get("reason_correct", 0))

        # --- Compute the basic confusion matrix. ---
        if gt == 1 and pred_is_vul:
            tp += 1
        elif gt == 0 and not pred_is_vul:
            tn += 1
        elif gt == 0 and pred_is_vul:
            fp += 1
        elif gt == 1 and not pred_is_vul:
            fn += 1

        # --- Compute detailed reasoning statistics. ---
        # Determine which key stores this result.
        p_key = "corr" if judge_pred_correct == 1 else "wrong"
        r_key = "corr" if judge_reason_correct == 1 else "wrong"
        final_key = f"{p_key}_{r_key}"
        
        details[gt][final_key] += 1

    # 2. Compute metrics.
    accuracy = safe_div(tp + tn, total)
    precision = safe_div(tp, tp + fp)
    recall = safe_div(tp, tp + fn)
    f1 = safe_div(2 * precision * recall, precision + recall)

    # 3. Print the report.
    print("\n" + "="*50)
    print("📊 模型评估报告 (Model Evaluation Report)")
    print("="*50)
    print(f"总样本数 (Total Samples): {total}")
    
    print("\n🔹 基础指标 (Basic Metrics):")
    print(f"{'Accuracy (准确率):':<25} {accuracy:.4f} ({accuracy*100:.2f}%)")
    print(f"{'Precision (精确率):':<25} {precision:.4f} ({precision*100:.2f}%)")
    print(f"{'Recall (召回率):':<25} {recall:.4f} ({recall*100:.2f}%)")
    print(f"{'F1 Score (F1分数):':<25} {f1:.4f}")

    print("\n🔹 混淆矩阵 (Confusion Matrix):")
    print(f"{'TP (真阳性 - 报对漏洞):':<30} {tp}")
    print(f"{'TN (真阴性 - 报对安全):':<30} {tn}")
    print(f"{'FP (假阳性 - 误报):':<30} {fp}")
    print(f"{'FN (假阴性 - 漏报):':<30} {fn}")

    print("\n" + "-"*50)
    print("🧠 详细推理质量分析 (Reasoning Analysis)")
    print("-"*50)

    # Print GT=1 cases.
    d1 = details[1]
    print("\n📌 真实标签 = 1 (Vulnerable/有漏洞) 的样本分布:")
    print(f"1. 判断正确 ✅ & 理由正确 ✅ : {d1['corr_corr']}")
    print(f"2. 判断正确 ✅ & 理由错误 ❌ : {d1['corr_wrong']}  <--(猜对了但理由不对)")
    print(f"3. 判断错误 ❌ & 理由正确 ✅ : {d1['wrong_corr']}  <--(罕见: Judge认为理由合理但结论下错了)")
    print(f"4. 判断错误 ❌ & 理由错误 ❌ : {d1['wrong_wrong']}  <--(完全错误)")
    
    subtotal_1 = sum(d1.values())
    print(f"   --> 合计 (Total GT=1): {subtotal_1}")

    # Print GT=0 cases.
    d0 = details[0]
    print("\n📌 真实标签 = 0 (Safe/无漏洞) 的样本分布:")
    print(f"1. 判断正确 ✅ & 理由正确 ✅ : {d0['corr_corr']}")
    print(f"2. 判断正确 ✅ & 理由错误 ❌ : {d0['corr_wrong']}")
    print(f"3. 判断错误 ❌ & 理由正确 ✅ : {d0['wrong_corr']}")
    print(f"4. 判断错误 ❌ & 理由错误 ❌ : {d0['wrong_wrong']}")
    
    subtotal_0 = sum(d0.values())
    print(f"   --> 合计 (Total GT=0): {subtotal_0}")
    print("="*50)

if __name__ == "__main__":
    analyze(RESULT_FILE)
