# test.py
# RAG + Cot+ cpg
import json
import os
import threading
from pathlib import Path
from typing import Any, Dict, List
from concurrent.futures import ThreadPoolExecutor, as_completed
from tqdm import tqdm
from openai import OpenAI

# Import local modules.
from .build_prompt import build_code_prediction_prompts, build_judge_prompts
# Assumes rag_engine.py is in the same package.
from .rag_engine import VulnRAG

# ================= Config =================
def require_env(name: str) -> str:
    value = os.getenv(name)
    if not value:
        raise RuntimeError(f"Missing required environment variable: {name}")
    return value


MY_API_KEY = require_env("CODE_API_KEY")
BASE_URL = os.getenv("CODE_BASE_URL", "https://dashscope.aliyuncs.com/compatible-mode/v1")
CODE_MODEL_NAME = os.getenv("CODE_MODEL_NAME", "qwen3-32b")

JUDGE_API_KEY = require_env("JUDGE_API_KEY")
JUDGE_BASE_URL = os.getenv("JUDGE_BASE_URL", "https://api.deepseek.com")
JUDGE_MODEL_NAME = os.getenv("JUDGE_MODEL_NAME", "deepseek-chat")

# Path config.
CODE_ROOT = Path("D:/LIHAOZE/bishe/thecode/ddd/dataset_v1")
# CODE_ROOT = Path("D:/LIHAOZE/bishe/thecode/ddd/dataset_v2")
DATASET_FILE = CODE_ROOT / "BaseCodeFilesReason.json" # Used as both the test set and knowledge-base source.
OUTPUT_JSON = CODE_ROOT / f"{CODE_MODEL_NAME}_RAG_COT2_Results.json" # Rename to distinguish this output.
RAG_DB_DIR = CODE_ROOT / "chroma_db_storage" 

# === Strategy switches ===
ENABLE_RAG = True
RAG_TOP_K = 3         # Retrieve the 3 most similar cases.
MAX_WORKERS =16       # Lower concurrency slightly when RAG is enabled to avoid embedding API congestion.

# Initialize clients.
client = OpenAI(api_key=MY_API_KEY, base_url=BASE_URL)
client_judge = OpenAI(api_key=JUDGE_API_KEY, base_url=JUDGE_BASE_URL)

rag_engine = None # Global variable.

# ================= Utilities =================

def extract_json_from_text(text: str) -> str:
    """Extract a JSON string."""
    text = text.strip()
    try:
        json.loads(text)
        return text
    except:
        pass
    if "```json" in text:
        start = text.find("```json") + 7
        end = text.find("```", start)
        if end != -1: return text[start:end].strip()
    if "{" in text:
        # Find the final } to include the complete JSON object.
        start = text.find("{")
        end = text.rfind("}")
        if start != -1 and end > start: return text[start : end + 1]
    return text

# def call_code_llm(system_prompt: str, user_prompt: str) -> Dict[str, Any]:
#     try:
#         response = client.chat.completions.create(
#             model=CODE_MODEL_NAME,
#             messages=[
#                 {"role": "system", "content": system_prompt},
#                 {"role": "user", "content": user_prompt},
#             ],
#             # Note: even though we manually write the CoT prompt, setting this to True is fine.
#             # However, Qwen API enable_thinking usually means exposing its internal thinking process.
#             # To fully control CoT in the prompt, set it to False and rely entirely on prompt instructions.
#             extra_body={"enable_thinking": False}, 
#             temperature=0.0, # Keep deterministic output.
#             timeout=80       # Increase timeout because CoT output is longer.
#         )
#         content = response.choices[0].message.content or ""
#         json_text = extract_json_from_text(content)
#         data = json.loads(json_text)
#     except Exception as e:
#         return {
#             "is_vulnerable": False,
#             "vuln_type": "API_ERROR",
#             "prediction_reason": f"System Error: {str(e)}",
#             "raw_output": str(e)
#         }

#     # Robustness handling.
#     raw_is_vul = data.get("is_vulnerable", False)
#     if isinstance(raw_is_vul, str):
#         is_vul = raw_is_vul.lower() in ["true", "yes", "1"]
#     else:
#         is_vul = bool(raw_is_vul)

#     return {
#         "is_vulnerable": is_vul,
#         "vuln_type": str(data.get("vuln_type", "UNKNOWN")),
#         # This may actually contain the long CoT generated by the model.
#         "prediction_reason": str(data.get("prediction_reason", "")),
#     }


# Updated utility function in test.py.

def call_code_llm(system_prompt: str, user_prompt: str) -> Dict[str, Any]:
    try:
        response = client.chat.completions.create(
            model=CODE_MODEL_NAME,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            # extra_body={"enable_thinking": False},
            temperature=0.0,
            timeout=80 
        )
        content = response.choices[0].message.content or ""
        
        # === Debug point: print content to inspect the current reasoning process. ===
        # print("RAW_OUTPUT:", content) 
        
        # Extract JSON.
        json_text = extract_json_from_text(content)
        data = json.loads(json_text)
        
        # If needed, extract <thinking> into prediction_reason to help the judge evaluate it.
        # This lets the judge see the full chain of thought while keeping the JSON structure simple.
        thinking_content = ""
        if "<thinking>" in content and "</thinking>" in content:
            start = content.find("<thinking>") + 10
            end = content.find("</thinking>")
            thinking_content = content[start:end].strip()
        
        # Combine: reason = short summary plus optional detailed reasoning.
        final_reason = data.get("prediction_reason", "")
        # Append chain-of-thought here if the judge should see it.
        # final_reason = f"Summary: {final_reason}\n\nDetailed Thought Process:\n{thinking_content}"
        
        data["prediction_reason"] = final_reason

    except Exception as e:
        return {
            "is_vulnerable": False,
            "vuln_type": "PARSE_ERROR",
            "prediction_reason": f"Error: {str(e)}",
            "raw_output": str(e) # Useful for debugging.
        }

    # ... Boolean normalization below is unchanged.
    raw_is_vul = data.get("is_vulnerable", False)
    if isinstance(raw_is_vul, str):
        is_vul = raw_is_vul.lower() in ["true", "yes", "1"]
    else:
        is_vul = bool(raw_is_vul)

    return {
        "is_vulnerable": is_vul,
        "vuln_type": str(data.get("vuln_type", "UNKNOWN")),
        "prediction_reason": str(data.get("prediction_reason", "")),
    }

def call_judge_llm(system_prompt: str, user_prompt: str) -> Dict[str, Any]:
    try:
        response = client_judge.chat.completions.create(
            model=JUDGE_MODEL_NAME,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            temperature=0.0,
            timeout=60
        )
        content = response.choices[0].message.content or ""
        json_text = extract_json_from_text(content)
        data = json.loads(json_text)
    except Exception as e:
        return {
            "prediction_correct": 0, "reason_correct": 0,
            "missing_points": [f"Judge Error: {str(e)}"], "wrong_points": []
        }

    pc = data.get("prediction_correct", 0)
    rc = data.get("reason_correct", 0)
    return {
        "prediction_correct": 1 if pc else 0,
        "reason_correct": 1 if rc else 0,
        "missing_points": data.get("missing_points", []),
        "wrong_points": data.get("wrong_points", []),
    }

# ================= Core processing logic =================

def process_single_sample(sample: Dict[str, Any]) -> Dict[str, Any]:
    sample_id = str(sample.get("id", "unknown"))
    gt_label = int(sample.get("label", 0))
    code = sample.get("code", "")
    language = sample.get("language", "C")
    
    # 1. RAG retrieval.
    similar_cases = []
    retrieved_ids = []
    
    if ENABLE_RAG and rag_engine:
        # Pass exclude_id to prevent leakage.
        similar_cases = rag_engine.search(
            query_code=code,
            rerank_top_k=RAG_TOP_K,
            exclude_id=sample_id
        )
        # Record retrieved IDs for analysis.
        retrieved_ids = [c.get('id', 'N/A') for c in similar_cases]

    # 2. Predict with CoT.
    # The prompt includes retrieved cases and CoT instructions.
    code_sys, code_user = build_code_prediction_prompts(
        code=code, 
        language=language, 
        similar_cases=similar_cases
    )
    code_res = call_code_llm(code_sys, code_user)

    # 3. Judge the prediction.
    judge_sys, judge_user = build_judge_prompts(
        code=code,
        language=language,
        gt_label=gt_label,
        reference_reason=sample.get("reason", ""),
        model_is_vul=code_res["is_vulnerable"],
        model_vuln_type=code_res["vuln_type"],
        model_reason=code_res["prediction_reason"], # Contains CoT content.
    )
    judge_res = call_judge_llm(judge_sys, judge_user)

    # 4. Assemble the result.
    return {
        "id": sample_id,
        "code": code,
        "gt_label": gt_label,
        # RAG information.
        "rag_retrieved_ids": retrieved_ids,
        "rag_context_count": len(similar_cases),
        # Prediction result.
        "pred_is_vul": code_res["is_vulnerable"],
        "pred_vuln_type": code_res["vuln_type"],
        "pred_reason": code_res["prediction_reason"],
        # Judge result.
        "prediction_correct": judge_res["prediction_correct"],
        "reason_correct": judge_res["reason_correct"],
        "missing_points": judge_res["missing_points"],
        "wrong_points": judge_res["wrong_points"]
    }

# ================= Main program =================

def main():
    global rag_engine
    
    # 1. Initialize RAG.
    if ENABLE_RAG:
        if not os.path.exists(DATASET_FILE):
            print(f"❌ 找不到数据文件: {DATASET_FILE}")
            return
            
        print("🔧 初始化 RAG 引擎 (Loading Knowledge Base)...")
        # On the first run, read DATASET_FILE and call the embedding API.
        # On later runs, load RAG_DB_DIR directly.
        rag_engine = VulnRAG(
            dataset_path=str(DATASET_FILE), 
            persist_dir=str(RAG_DB_DIR)
        )

    # 2. Read test data.
    with open(DATASET_FILE, "r", encoding="utf-8") as f:
        dataset = json.load(f)

    print(f"🚀 开始 RAG+CoT 测试，共 {len(dataset)} 条样本...")

    # 3. Initialize the result file.
    with open(OUTPUT_JSON, "w", encoding="utf-8") as f:
        f.write("[\n")

    file_lock = threading.Lock()
    is_first = True
    pbar = tqdm(total=len(dataset), unit="sample")

    # 4. Run concurrently.
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        future_to_sample = {executor.submit(process_single_sample, s): s for s in dataset}

        for future in as_completed(future_to_sample):
            try:
                result = future.result()
                
                # Write to file.
                with file_lock:
                    with open(OUTPUT_JSON, "a", encoding="utf-8") as f:
                        if not is_first: f.write(",\n")
                        else: is_first = False
                        json.dump(result, f, ensure_ascii=False, indent=4)
                        
            except Exception as e:
                print(f"Error processing sample: {e}")
            
            pbar.update(1)

    # Finish.
    with open(OUTPUT_JSON, "a", encoding="utf-8") as f:
        f.write("\n]")
    pbar.close()
    print(f"\n✅ 任务完成！RAG-CoT 结果已保存至: {OUTPUT_JSON}")

if __name__ == "__main__":
    main()
